apiVersion: apps/v1
kind: Deployment
metadata:
  name: rapid-competitions
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rapid-competitions
  template:
    metadata:
      labels:
        app: rapid-competitions
    spec:
      containers:
      - name: rapid-competitions
        image: your-dockerhub-username/rapid-competitions:latest
        ports:
        - containerPort: 8000
        env:
        - name: DEBUG
          value: "False"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"