apiVersion: v1
kind: Service
metadata:
  name: rapid-competitions
  namespace: production
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
  selector:
    app: rapid-competitions
